modales/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('productos.urls', namespace='productos')),
]

productos/urls.py
from django.conf.urls import url
from productos.views import ListadoProductos, CrearProducto, ModificarProducto, DetalleProducto, CrearProveedor, ListadoProveedores, \
    ModificarProveedor, DetalleProveedor, CrearCompra, ModificarCompra, ListadoCompras

urlpatterns = [
    url(r'^$', ListadoProductos.as_view(), name="listado_productos"),
    url(r'^proveedores/$', ListadoProveedores.as_view(), name="listado_proveedores"),
    url(r'^crear_producto/$', CrearProducto.as_view(), name="crear_producto"),
    url(r'^modificar_producto/(?P<pk>.+)/$',ModificarProducto.as_view(), name="modificar_producto"),
    url(r'^detalle_producto/(?P<pk>.+)/$',DetalleProducto.as_view(), name="detalle_producto"),
    url(r'^crear_proveedor/$', CrearProveedor.as_view(), name="crear_proveedor"),
    url(r'^modificar_proveedor/(?P<pk>.+)/$',ModificarProveedor.as_view(), name="modificar_proveedor"),
    url(r'^detalle_proveedor/(?P<pk>.+)/$',DetalleProveedor.as_view(), name="detalle_proveedor"),
    url(r'^crear_compra/$', CrearCompra.as_view(), name="crear_compra"),
    url(r'^modificar_compra/(?P<pk>.+)/$',ModificarCompra.as_view(), name="modificar_compra"),
    url(r'^compras/$', ListadoCompras.as_view(), name="listado_compras"),
]

productos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Producto(models.Model):
    descripcion = models.CharField(max_length=100, unique=True)
    marca = models.CharField(max_length=40,blank=True)
    precio = models.DecimalField(max_digits=15, decimal_places=5, default=0)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.descripcion

class Proveedor(models.Model):
    ruc = models.CharField(unique=True,max_length=11)
    razon_social = models.CharField(max_length=150)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=15,null=True)
    correo = models.EmailField(null=True)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.razon_social

class Compra(models.Model):
    proveedor = models.ForeignKey(Proveedor)
    fecha = models.DateField(auto_now_add=True)

class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra)
    producto = models.ForeignKey(Producto)
    cantidad = models.DecimalField(max_digits=5, decimal_places=2)
    precio_compra = models.DecimalField(max_digits=5,decimal_places=2)

productos/forms.py
from django import forms
from django.forms.models import modelformset_factory, inlineformset_factory
from productos.models import Producto, Proveedor, Compra, DetalleCompra


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ['descripcion', 'marca', 'precio', 'estado']

    def __init__(self, *args, **kwargs):
        super(ProductoForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            if field <> 'estado':
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

class ProveedorForm(forms.ModelForm):

    class Meta:
        model = Proveedor
        fields = ['ruc', 'razon_social', 'direccion', 'telefono','correo', 'estado']

    def __init__(self, *args, **kwargs):
        super(ProveedorForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            if field <> 'estado':
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

class CompraForm(forms.ModelForm):

    class Meta:
        model = Compra
        fields = ['proveedor']

    def __init__(self, *args, **kwargs):
        super(CompraForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class DetalleCompraForm(forms.ModelForm):

    class Meta:
        model = DetalleCompra
        fields = ['producto','cantidad','precio_compra']

    def __init__(self, *args, **kwargs):
        super(DetalleCompraForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    def clean_cantidad(self):
        cantidad = self.cleaned_data['cantidad']
        if cantidad == '':
            raise forms.ValidationError("Debe ingresar una cantidad valida")
        return cantidad

    def clean_precio_compra(self):
        precio = self.cleaned_data['precio_compra']
        if precio == '':
            raise forms.ValidationError("Debe ingresar un precio valido")
        return precio

DetalleCompraFormSet = inlineformset_factory(Compra, DetalleCompra, form=DetalleCompraForm, extra=4)

productos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.list import ListView
from productos.forms import ProductoForm, ProveedorForm, CompraForm, DetalleCompraFormSet
from productos.models import Producto, Proveedor, Compra, DetalleCompra
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
from django.http.response import HttpResponseRedirect

class ListadoProductos(ListView):
    model = Producto
    template_name = 'productos.html'
    context_object_name = 'productos'

class ListadoProveedores(ListView):
    model = Proveedor
    template_name = 'proveedores.html'
    context_object_name = 'proveedores'

class ListadoCompras(ListView):
    model = Compra
    template_name = 'compras.html'
    context_object_name = 'compras'

class CrearProducto(CreateView):
    template_name = 'producto.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:listado_productos')

class CrearProveedor(CreateView):
    template_name = 'proveedor.html'
    form_class = ProveedorForm
    success_url = reverse_lazy('productos:listado_proveedores')

class ModificarProducto(UpdateView):
    model = Producto
    template_name = 'producto.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:listado_productos')

class ModificarProveedor(UpdateView):
    model = Proveedor
    template_name = 'proveedor.html'
    form_class = ProveedorForm
    success_url = reverse_lazy('productos:listado_proveedores')

class ModificarCompra(UpdateView):
    model = Compra
    template_name = 'compra.html'
    form_class = CompraForm
    success_url = reverse_lazy('productos:listado_compras')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalles = DetalleCompra.objects.filter(compra=self.object).order_by('pk')
        detalles_data = []
        for detalle in detalles:
            d = {'producto': detalle.producto,
                 'cantidad': detalle.cantidad,
                 'precio_compra': detalle.precio_compra}
            detalles_data.append(d)
        detalle_compra_form_set = DetalleCompraFormSet(initial=detalles_data)
        return self.render_to_response(self.get_context_data(form=form,
                                                             detalle_compra_form_set=detalle_compra_form_set))


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_compra_form_set = DetalleCompraFormSet(request.POST)
        if form.is_valid() and detalle_compra_form_set.is_valid():
            return self.form_valid(form, detalle_compra_form_set)
        else:
            return self.form_invalid(form, detalle_compra_form_set)


    def form_valid(self, form, detalle_compra_form_set):
        self.object = form.save()
        detalle_compra_form_set.instance = self.object
        DetalleCompra.objects.filter(compra = self.object).delete()
        detalle_compra_form_set.save()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form, detalle_compra_form_set):
        return self.render_to_response(self.get_context_data(form=form,
                                                             detalle_compra_form_set = detalle_compra_form_set))

class DetalleProducto(DetailView):
    model = Producto
    template_name = 'detalle_producto.html'

class DetalleProveedor(DetailView):
    model = Proveedor
    template_name = 'detalle_proveedor.html'

class CrearCompra(CreateView):
    model = Compra
    template_name = 'compra.html'
    form_class = CompraForm
    success_url = reverse_lazy('productos:listado_compras')

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_orden_compra_formset=DetalleCompraFormSet()
        return self.render_to_response(self.get_context_data(form=form,
                                                             detalle_compra_form_set=detalle_orden_compra_formset))

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_compra_form_set = DetalleCompraFormSet(request.POST)
        if form.is_valid() and detalle_compra_form_set.is_valid():
            return self.form_valid(form, detalle_compra_form_set)
        else:
            return self.form_invalid(form, detalle_compra_form_set)


    def form_valid(self, form, detalle_compra_form_set):
        self.object = form.save()
        detalle_compra_form_set.instance = self.object
        detalle_compra_form_set.save()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form, detalle_compra_form_set):
        return self.render_to_response(self.get_context_data(form=form,
                                                             detalle_compra_form_set = detalle_compra_form_set))

productos/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Modales</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css'  %}"/>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}" charset="UTF-8"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" charset="UTF-8"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
</head>
<body>
<div id="page-wrapper">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">PythonPiura</a>
        </div>
        <ul class="nav navbar-nav">
          <li>
              <a href="{% url 'productos:listado_productos' %}">Productos</a>
          </li>
          <li>
              <a href="{% url 'productos:listado_proveedores' %}">Proveedores</a>
          </li>
          <li>
              <a href="{% url 'productos:listado_compras' %}">Compras</a>
          </li>
        </ul>
        </div>
    </nav>

    <div class="container-fluid">
    {% block cuerpo %}

    {% endblock cuerpo %}
    </div>
</div>
</body>
</html>

productos/templates/compra.html
{% extends "base.html" %}
{% block cuerpo %}

{% if object %}
<form role="form" action="{% url 'productos:modificar_compra' object.pk %}" method="post">
	<h3>Modificar Compra</h3>
{% else %}
<form role="form" action="{% url 'productos:crear_compra' %}" method="post">
	<h3>Crear Compra</h3>
{% endif %}
	{% csrf_token %}
	<div class="panel panel-default">
		<div class="panel-body">
			{{ form.as_p }}
			{{ detalle_compra_form_set.management_form }}
			{% for detalle_compra_form in detalle_compra_form_set %}
				<div class="row">
					<div class="col-lg-4">
						<label>Producto</label>
						{% if detalle_compra_form.producto.errors %}
							{% for error in detalle_compra_form.producto.errors %}
							<div class="alert alert-danger alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<strong>Error: </strong> {{ error|escape }}
							</div>
							{% endfor %}
						{% endif %}
						{{ detalle_compra_form.producto }}
					</div>
					<div class="col-lg-4">
						<label>Cantidad</label>
						{% if detalle_compra_form.cantidad.errors %}
							{% for error in detalle_compra_form.cantidad.errors %}
							<div class="alert alert-danger alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<strong>Error: </strong> {{ error|escape }}
							</div>
							{% endfor %}
						{% endif %}
						{{ detalle_compra_form.cantidad }}
					</div>
					<div class="col-lg-4">
						<label>Precio</label>
						{% if detalle_compra_form.precio_compra.errors %}
							{% for error in detalle_compra_form.precio_compra.errors %}
							<div class="alert alert-danger alert-dismissible" role="alert">
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<strong>Error: </strong> {{ error|escape }}
							</div>
							{% endfor %}
						{% endif %}
						{{ detalle_compra_form.precio_compra }}
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
	<div class="col-lg-12 text-right">
		<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
		<a type="button" class="btn btn-default" href="{% url 'productos:listado_compras' %}">
			Cancelar
		</a>
	</div>
</form>
{% endblock cuerpo %}

productos/templates/compras.html
{% extends "base.html" %}
{% block cuerpo %}
<h3>Compras</h3>
<div class="row">
	<div class="col-lg-10">
		<a href="{% url 'productos:crear_compra' %}" class="btn btn-primary">
			Crear
		</a>
	</div>
</div>
<hr/>
<div class="row">
	<div class="col-lg-12">
		<table id="tabla" class="display" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th class="text-center">PROVEEDOR</th>
					<th class="text-center">FECHA</th>
					<th class="text-center">ACCIONES</th>
				</tr>
			</thead>
			<tbody>
			{% for compra in compras %}
                <tr>
                    <td>{{ compra.proveedor }}</td>
                    <td>{{ compra.fecha }}</td>
                    <td class="text-center">
                        <a href="#" class="btn">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <a href="{% url 'productos:modificar_compra' compra.pk %}" class="btn">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    </td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>
<script>
$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/localizacion/es_ES.json"
        }
    } );
});
</script>
{% endblock cuerpo %}

productos/templates/detalle_producto.html
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-lg-7">
				<h3>{{ object.descripcion }}</h3>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<label>MARCA:</label>
				<p>{{ object.marca }}</p>
				<label>PRECIO:</label>
				<p>{{ object.precio }}</p>
				<label>ESTADO:</label>
				{% if object.estado %}
					<p>ACTIVO</p>
				{% else %}
					<p>INACTIVO</p>
				{% endif %}
			</div>
		</div>
	</div>
</div>

productos/templates/detalle_proveedor.html
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">x</button>
			<h3>Detalle Proveedor</h3>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="col-lg-4">
					<label>RUC:</label>
					<p>{{ object.ruc }}</p>
					<label>RAZÓN SOCIAL:</label>
					<p>{{ object.razon_social }}</p>
					<label>DIRECCIÓN:</label>
					<p>{{ object.direccion }}</p>
					<label>TELÉFONO:</label>
					<p>{{ object.telefono }}</p>
					<label>CORREO:</label>
					<p>{{ object.correo }}</p>
					<label>ESTADO:</label>
					{% if object.estado %}
						<p>ACTIVO</p>
					{% else %}
						<p>INACTIVO</p>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<div class="col-lg-12 text-right">
				<button type="button" class="btn btn-primary" onclick="return cerrar_modal()">
					Aceptar
				</button>
			</div>
		</div>
	</div>
</div>

productos/templates/producto.html
{% if object %}
<form role="form" action="{% url 'productos:modificar_producto' object.pk %}" method="post">
{% else %}
<form role="form" action="{% url 'productos:crear_producto' %}" method="post">
{% endif %}
	{% csrf_token %}
	<div class="panel panel-default">
		<div class="panel-body">
			{{ form.as_p }}
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12 text-right">
			<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
			<button type="button" class="btn btn-default" onclick="return cerrar_modal()">
				Cancelar
			</button>
		</div>
	</div>
</form>

productos/templates/productos.html
{% extends "base.html" %}
{% block cuerpo %}
<h3>Productos</h3>
<div class="row">
	<div class="col-lg-10">
		<a onclick="return abrir_modal('{% url 'productos:crear_producto' %}','Productos / Nuevo')" class="btn btn-primary">
			Crear
		</a>
	</div>
</div>
<hr/>
<div class="row">
	<div class="col-lg-12">
		<table id="tabla" class="display" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th class="text-center">DESCRIPCION</th>
					<th class="text-center">MARCA</th>
					<th class="text-center">PRECIO</th>
					<th class="text-center">ESTADO</th>
					<th class="text-center">ACCIONES</th>
				</tr>
			</thead>
			<tbody>
			{% for producto in productos %}
                <tr>
                    <td>{{ producto.descripcion }}</td>
                    <td>{{ producto.marca }}</td>
                    <td>{{ producto.precio }}</td>
                    {% if producto.estado %}
                    <td>ACTIVO</td>
                    {% else %}
                    <td>INACTIVO</td>
                    {% endif %}
                    <td class="text-center">
                        <a onclick="return abrir_modal('{% url 'productos:detalle_producto' producto.pk %}','Productos / {{ producto.descripcion }}')" class="btn">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <a onclick="return abrir_modal('{% url 'productos:modificar_producto' producto.pk %}','Productos / {{ producto.descripcion }}')" class="btn">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    </td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>
<div id="popup"></div>
<script>
var modal;
function abrir_modal(url, titulo)
{
    modal = $('#popup').dialog(
    {
        title: titulo,
        modal: true,
        width: 500,
        resizable: false
    }).dialog('open').load(url)
}

function cerrar_modal()
{
    modal.dialog("close");
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/localizacion/es_ES.json"
        }
    } );
});
</script>
{% endblock cuerpo %}

productos/templates/proveedor.html
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		{% if object %}
		<form role="form" action="{% url 'productos:modificar_proveedor' object.pk %}" method="post">
		{% else %}
		<form role="form" action="{% url 'productos:crear_proveedor' %}" method="post">
		{% endif %}
			<div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>Modificar Proveedor</h3>
            </div>
            <div class="modal-body">
				{% csrf_token %}
				<div class="panel panel-default">
					<div class="panel-body">
						{{ form.as_p }}
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-lg-12 text-right">
					<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
					<button type="button" class="btn btn-default" onclick="return cerrar_modal()">
						Cancelar
					</button>
				</div>
			</div>
		</form>
	</div>
</div>

productos/templates/proveedores.html
{% extends "base.html" %}
{% block cuerpo %}
<h3>Proveedores</h3>
<div class="row">
	<div class="col-lg-10">
		<a onclick="return abrir_modal('{% url 'productos:crear_proveedor' %}')" class="btn btn-primary">
			Crear
		</a>
	</div>
</div>
<hr/>
<div class="row">
	<div class="col-lg-12">
		<table id="tabla" class="display" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th class="text-center">RUC</th>
					<th class="text-center">RAZON SOCIAL</th>
					<th class="text-center">DIRECCION</th>
					<th class="text-center">ESTADO</th>
					<th class="text-center">ACCIONES</th>
				</tr>
			</thead>
			<tbody>
			{% for proveedor in proveedores %}
                <tr>
                    <td>{{ proveedor.ruc }}</td>
                    <td>{{ proveedor.razon_social }}</td>
                    <td>{{ proveedor.direccion }}</td>
                    {% if proveedor.estado %}
                    <td>ACTIVO</td>
                    {% else %}
                    <td>INACTIVO</td>
                    {% endif %}
                    <td class="text-center">
                        <a onclick="return abrir_modal('{% url 'productos:detalle_proveedor' proveedor.pk %}')" class="btn">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <a onclick="return abrir_modal('{% url 'productos:modificar_proveedor' proveedor.pk %}')" class="btn">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    </td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>
<div id="popup" class="modal fade" role="dialog">

</div>
<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/localizacion/es_ES.json"
        }
    } );
});
</script>
{% endblock cuerpo %}